#INCLUDE "TOTVS.CH"

/*-----------------------------------------------------------------------------------------------
{Protheus.doc} MT910MNU
Ponto de Entrada no menu do MATA910 - Nota manual
@author  Mário A. Cavenaghi - EthosX
@since   15/10/2020
@release P12.1.25
-------------------------------------------------------------------------------------------------
*/
User Function MT910MNU

	aAdd(aRotina, {"Digitação D.I.", "U_FSFISA01", 0, 4, 0, NIL})

Return(.T.)
